FROM urm.nvidia.com/docker/tensorflow/build:latest-python3.9
WORKDIR /xla
ADD . /xla 
RUN apt update && \
    apt upgrade libcudnn8-dev=8.9.0.131-1+cuda11.8 libcudnn8=8.9.0.131-1+cuda11.8 -y && \
    update-alternatives --set cuda /usr/local/cuda-11.8 
RUN ./configure
